# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
torch_dtype: bfloat16
tokenizer_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

tag: llama-3

dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0

dataset_splits:
- train_prefs
- test_prefs

preprocessing_num_workers: 12

# Trainer arguments
use_flash_attention_2: true
bf16: true
do_eval: false
eval_strategy: steps
eval_steps: 200
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
optim: adamw_torch
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
save_strategy: "epoch"
save_steps: 1
num_train_epochs: 1
save_total_limit: 1
save_only_model: true
seed: 42
warmup_ratio: 0.1
report_to: tensorboard



loss_type: mipo
beta: 20.0
output_dir: saved_models
deepspeed: configs/deepspeed/ds_config.json

